### PR TITLE
Moat integration

### PR DESCRIPTION
**Pull request by leggsimon**
@adgad @VladDubrovskis @andrewgeorgiou1981

### CODE REVIEW

**Comment by adgad** [comment]
👍

**Comment by commuterjoy** [comment]
Are you removing chartbeat at the same time?

**Comment by commuterjoy** [comment]
PS. should use feature flags for third party stuff

**Comment by adgad** [comment]
Not yet. Want to do some comparison of the data with chartbeat first somewhere it's being used, then probably remove in a later major version. 

o-ads is used across several products. We shall be using a flag to turn it on/off for next within next-ads-component :)

**Comment by adgad** [comment]
(it's off until specifically configured by a site)

**Comment by commuterjoy** [comment]
perfect - thanks

**Comment by leggsimon** [comment]
We'll wait for Moat to QA before merging this.

**Pull request merged**
