### PR TITLE
Added codeowners file

### PR DESCRIPTION
**Pull request by carlesandres**
Just added a CODEOWNERS file

### CODE REVIEW

**Comment by JakeChampion** [comment]
@carlesandres there already is one -- https://github.com/Financial-Times/o-ads/blob/master/.github/CODEOWNERS

**Comment by carlesandres** [comment]
Argh! I hadn't noticed. Is it best practice to put it in the `.github` folder then?

**Comment by carlesandres** [comment]
Closing down as I can see it doesn't make a difference if it's the root, `/docs` or `/.github`

**Comment by JakeChampion** [comment]
.github folder is the best place for the github specific files 👍

**Comment by carlesandres** [comment]
Good to know. I guess we are doing it wrongly in most repos at the moment, then.

**Comment by JakeChampion** [comment]
The reason it was not working is because the @Financial-Times/ads team did not have access to the repo. I have now added the team as admins on the repo, now it will work

**Comment by carlesandres** [comment]
Nice one, thanks!

**Comment by oliverturner** [comment]
> The reason it was not working is because the @Financial-Times/ads team did not have access to the repo. I have now added the team as admins on the repo, now it will work

This - and the point about file location - is super useful insight… thanks as always @JakeChampion 🙌

**Pull request closed without merging**
