### PR TITLE
ensure ads switch to silent mode after output

### PR DESCRIPTION
**Pull request by i-like-robots**
For consistency with other modules, E.G.:

https://github.com/Financial-Times/o-typography/blob/master/main.scss#L141
https://github.com/Financial-Times/o-buttons/blob/master/main.scss#L47
https://github.com/Financial-Times/o-expander/blob/master/main.scss#L73

### CODE REVIEW

**Comment by adgad** [comment]
👍 (the saucelabs builds fail on forks)

**Comment by i-like-robots** [comment]
Ah OK... I don't have access to this repo so I can't merge either =/

**Comment by adgad** [comment]
Merged and given origami-collaborators access :)

**Comment by i-like-robots** [comment]
ta!

**Pull request merged**
